# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      TOOLS_BIN: tools/bin
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache required binary files
        uses: actions/cache@v2
        id: cache
        with:
          path: tools/bin
          key: ${{ runner.os }}-${{ hashFiles('tools/bin/tools.md') }}

      - name: Install Dependencies
        env:
          RH_PASSWORD: ${{ secrets.RH_PASSWORD }}
          RH_USER: ${{ secrets.RH_USER }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: "${GITHUB_WORKSPACE}/installDependencies.sh"

      - name: Test Installed
        run: |
          echo "[oc output] " && "${TOOLS_BIN}/ocv4.5.0" version
          echo "[opm downstream output] " && "${TOOLS_BIN}/opmdownv1.14.3" version
          echo "[opm upstream output] " && "${TOOLS_BIN}/opmupv1.15.1" version

